/**
 * AI Interview Prep engine.
 * If ANTHROPIC_API_KEY is set, questions and feedback are generated by
 * Claude, tailored to the role/skills and the candidate's actual answer.
 * If not, a curated question bank + heuristic feedback engine is used —
 * so interview prep always works, with or without an API key.
 */

const QUESTION_BANK = {
  behavioral: [
    "Tell me about a time you faced a conflict with a teammate. How did you resolve it?",
    "Describe a project you're most proud of and why.",
    "Tell me about a time you missed a deadline. What happened and what did you learn?",
    "Describe a situation where you had to learn something new very quickly.",
    "Tell me about a time you disagreed with a manager's decision.",
  ],
  general: [
    "Walk me through your resume.",
    "Why do you want to work here?",
    "Where do you see yourself in five years?",
    "What's your biggest weakness?",
    "Why should we hire you over other candidates?",
  ],
  technical: (skills = []) => {
    const s = skills.length ? skills : ["your primary tech stack"];
    return [
      `Explain a challenging bug you fixed involving ${s[0]}.`,
      `How would you design a scalable system using ${s.slice(0, 2).join(" and ") || s[0]}?`,
      `What are the trade-offs you consider when choosing ${s[0]} for a project?`,
      `Explain ${s[0]} to someone with no technical background.`,
      "How do you approach testing and debugging in your projects?",
    ];
  },
};

function ruleBasedQuestions(role = "", skills = []) {
  const technical = QUESTION_BANK.technical(skills);
  return [
    ...QUESTION_BANK.general.slice(0, 2),
    ...QUESTION_BANK.behavioral.slice(0, 2),
    ...technical.slice(0, 3),
  ].map((q, i) => ({ id: i + 1, question: q }));
}

function ruleBasedFeedback(question, answer = "") {
  const trimmed = answer.trim();
  const words = trimmed.split(/\s+/).filter(Boolean);
  const tips = [];
  let score = 50;

  if (words.length < 25) {
    tips.push("Your answer is quite short — add more concrete detail and a specific example.");
    score -= 15;
  } else if (words.length > 25) {
    score += 10;
  }

  const hasStar = /(situation|task|action|result)/i.test(trimmed);
  if (!hasStar && /time you|describe a|tell me about/i.test(question)) {
    tips.push("For behavioral questions, structure your answer with the STAR method: Situation, Task, Action, Result.");
    score -= 10;
  } else if (hasStar) {
    score += 15;
  }

  if (/\bum\b|\byou know\b|\bstuff\b|\bthing\b/i.test(trimmed)) {
    tips.push("Avoid filler words and vague terms like 'stuff' or 'thing' — be specific.");
    score -= 5;
  }

  if (!/\d/.test(trimmed)) {
    tips.push("Where possible, quantify your impact (%, time saved, users, revenue) to make it more convincing.");
  } else {
    score += 10;
  }

  score = Math.max(10, Math.min(95, score));

  if (tips.length === 0) tips.push("Solid, well-structured answer — keep this level of specificity in the real interview.");

  return { score, tips };
}

async function aiGenerateQuestions(role, skills) {
  const prompt = `Generate 7 realistic job interview questions for a candidate applying to the role "${role || "the listed job"}" with skills: ${(skills || []).join(", ") || "general"}. Mix general, behavioral, and technical questions relevant to the skills.

Return ONLY a JSON array, no other text, in this exact shape:
[{"id": 1, "question": "..."}, ...]`;

  const response = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": process.env.ANTHROPIC_API_KEY,
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify({
      model: process.env.ANTHROPIC_MODEL || "claude-sonnet-4-6",
      max_tokens: 600,
      messages: [{ role: "user", content: prompt }],
    }),
  });
  if (!response.ok) throw new Error(`AI API error: ${response.status}`);
  const data = await response.json();
  const text = (data.content || []).map((c) => c.text || "").join("");
  return JSON.parse(text.replace(/```json|```/g, "").trim());
}

async function aiGenerateFeedback(question, answer) {
  const prompt = `You are an experienced interview coach. The candidate was asked:
"${question}"

They answered:
"${answer}"

Give constructive feedback. Return ONLY a JSON object, no other text, in this exact shape:
{"score": <0-100 integer>, "tips": ["short actionable tip 1", "short actionable tip 2", "short actionable tip 3"]}`;

  const response = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": process.env.ANTHROPIC_API_KEY,
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify({
      model: process.env.ANTHROPIC_MODEL || "claude-sonnet-4-6",
      max_tokens: 400,
      messages: [{ role: "user", content: prompt }],
    }),
  });
  if (!response.ok) throw new Error(`AI API error: ${response.status}`);
  const data = await response.json();
  const text = (data.content || []).map((c) => c.text || "").join("");
  return JSON.parse(text.replace(/```json|```/g, "").trim());
}

async function generateQuestions(role, skills) {
  if (process.env.ANTHROPIC_API_KEY) {
    try {
      return await aiGenerateQuestions(role, skills);
    } catch {
      // fall through
    }
  }
  return ruleBasedQuestions(role, skills);
}

async function generateFeedback(question, answer) {
  if (process.env.ANTHROPIC_API_KEY) {
    try {
      return await aiGenerateFeedback(question, answer);
    } catch {
      // fall through
    }
  }
  return ruleBasedFeedback(question, answer);
}

module.exports = { generateQuestions, generateFeedback };
