// World-Scale Enterprise Job Index Data Repository
const worldJobDatabase = [
  // FRONTEND ROLES
  {
    _id: "global-fe-1",
    title: "Principal Frontend Architect (React / Next.js 14 / Micro-Frontends)",
    companyName: "Meta / Instagram Engineering",
    company: "Meta / Instagram Engineering",
    description: "Architecting high-scale global web surfaces serving 2 Billion+ active daily users using React Server Components, GraphQL Relay, and WebGL.",
    skills: ["React", "JavaScript", "TypeScript", "Next.js", "GraphQL", "Frontend", "Tailwind CSS"],
    location: "Bangalore (Remote Available)",
    jobType: "Full-time",
    workMode: "Remote",
    salaryMin: 4500000,
    salaryMax: 7000000,
    salary: "₹45 - ₹70 LPA",
    experienceRequired: 7,
    status: "open",
    createdAt: new Date(),
  },
  {
    _id: "mock-1",
    title: "Senior Frontend Engineer (React / Next.js)",
    companyName: "TechCorp Global",
    company: "TechCorp Global",
    description: "Building next-generation micro-frontend architectures with React, Redux Toolkit, and Tailwind CSS.",
    skills: ["React", "JavaScript", "Frontend", "Tailwind CSS", "TypeScript"],
    location: "Bangalore",
    jobType: "Full-time",
    workMode: "Remote",
    salaryMin: 1800000,
    salaryMax: 2800000,
    salary: "₹18 - ₹28 LPA",
    status: "open",
    createdAt: new Date(),
  },
  {
    _id: "mock-6",
    title: "UI/UX Frontend Specialist (Vue / React)",
    companyName: "Creative Design Hub",
    company: "Creative Design Hub",
    description: "Crafting ultra-responsive pixel-perfect web interfaces with Figma, React, Tailwind CSS, and Framer Motion.",
    skills: ["React", "Frontend", "Vue", "CSS", "UI/UX"],
    location: "Mumbai",
    jobType: "Full-time",
    workMode: "Hybrid",
    salaryMin: 1200000,
    salaryMax: 2000000,
    salary: "₹12 - ₹20 LPA",
    status: "open",
    createdAt: new Date(),
  },
  {
    _id: "mock-9",
    title: "Staff Frontend Architect (Next.js & WebGL)",
    companyName: "Vercel Enterprise Partner",
    company: "Vercel Enterprise Partner",
    description: "Engineered ultra-fast server-rendered React applications with Next.js 14, WebGL 3D graphics, and TypeScript.",
    skills: ["React", "Frontend", "Next.js", "TypeScript", "Tailwind"],
    location: "Bangalore",
    jobType: "Full-time",
    workMode: "Onsite",
    salaryMin: 2800000,
    salaryMax: 4200000,
    salary: "₹28 - ₹42 LPA",
    status: "open",
    createdAt: new Date(),
  },

  // BACKEND ROLES
  {
    _id: "global-be-1",
    title: "Distributed Backend Systems Architect (Go / Rust / Microservices)",
    companyName: "Uber Core Infrastructure",
    company: "Uber Core Infrastructure",
    description: "Building ultra-low-latency real-time geospatial dispatch engines and distributed fault-tolerant backend pipelines.",
    skills: ["Go", "Golang", "Backend", "Rust", "Microservices", "Kafka", "Redis", "Distributed Systems"],
    location: "Hyderabad",
    jobType: "Full-time",
    workMode: "Hybrid",
    salaryMin: 5000000,
    salaryMax: 8500000,
    salary: "₹50 - ₹85 LPA",
    experienceRequired: 8,
    status: "open",
    createdAt: new Date(),
  },
  {
    _id: "mock-2",
    title: "Backend Node.js API Architect",
    companyName: "CloudScale Systems",
    company: "CloudScale Systems",
    description: "Designing high-concurrency microservices APIs with Node.js, Express, MongoDB, and Redis caching.",
    skills: ["Node.js", "Express", "Backend", "MongoDB", "Redis", "API"],
    location: "Hyderabad",
    jobType: "Full-time",
    workMode: "Hybrid",
    salaryMin: 1600000,
    salaryMax: 2500000,
    salary: "₹16 - ₹25 LPA",
    status: "open",
    createdAt: new Date(),
  },
  {
    _id: "mock-7",
    title: "Lead Python Backend & Data Pipeline Engineer",
    companyName: "DataGrid Technologies",
    company: "DataGrid Technologies",
    description: "Building scalable distributed backend data processing systems using Python, Django, PostgreSQL, and Kafka.",
    skills: ["Python", "Backend", "Django", "PostgreSQL", "Kafka", "Node.js"],
    location: "Bangalore",
    jobType: "Full-time",
    workMode: "Onsite",
    salaryMin: 2200000,
    salaryMax: 3400000,
    salary: "₹22 - ₹34 LPA",
    status: "open",
    createdAt: new Date(),
  },
  {
    _id: "mock-8",
    title: "Java Microservices Backend Lead",
    companyName: "FinTech Enterprise",
    company: "FinTech Enterprise",
    description: "High-frequency financial backend transaction engines built on Java Spring Boot, Microservices, and Redis.",
    skills: ["Java", "Spring Boot", "Backend", "Microservices", "Redis"],
    location: "Delhi NCR",
    jobType: "Full-time",
    workMode: "Remote",
    salaryMin: 2400000,
    salaryMax: 3600000,
    salary: "₹24 - ₹36 LPA",
    status: "open",
    createdAt: new Date(),
  },

  // FULL STACK ROLES
  {
    _id: "global-fs-1",
    title: "Senior AI Full Stack Engineer (React / Python FastAPI / LLM Integration)",
    companyName: "OpenAI Platform Partner",
    company: "OpenAI Platform Partner",
    description: "Architecting autonomous generative AI assistants, vector search engines (Pinecone / Milvus), and modern React dashboards.",
    skills: ["React", "Python", "Full Stack", "FastAPI", "OpenAI", "Vector DB", "PostgreSQL"],
    location: "Bangalore",
    jobType: "Full-time",
    workMode: "Remote",
    salaryMin: 3500000,
    salaryMax: 6000000,
    salary: "₹35 - ₹60 LPA",
    experienceRequired: 5,
    status: "open",
    createdAt: new Date(),
  },
  {
    _id: "mock-3",
    title: "Full Stack MERN Developer",
    companyName: "Innovate AI Labs",
    company: "Innovate AI Labs",
    description: "End-to-end web application engineering combining React frontend and Express MongoDB backend engines.",
    skills: ["React", "Node.js", "Full Stack", "MongoDB", "Express", "Backend", "Frontend"],
    location: "Pune",
    jobType: "Full-time",
    workMode: "Remote",
    salaryMin: 1400000,
    salaryMax: 2200000,
    salary: "₹14 - ₹22 LPA",
    status: "open",
    createdAt: new Date(),
  },
  {
    _id: "mock-10",
    title: "Senior Full Stack Engineer (React + Python FastAPI)",
    companyName: "AI Unicorn Tech",
    company: "AI Unicorn Tech",
    description: "Architecting generative AI applications with React TypeScript frontends and Python FastAPI microservices.",
    skills: ["React", "Python", "Full Stack", "FastAPI", "PostgreSQL", "Frontend"],
    location: "Bangalore",
    jobType: "Full-time",
    workMode: "Hybrid",
    salaryMin: 2600000,
    salaryMax: 4000000,
    salary: "₹26 - ₹40 LPA",
    status: "open",
    createdAt: new Date(),
  },
  {
    _id: "mock-11",
    title: "Lead Full Stack Product Engineer",
    companyName: "Global SaaS Platform",
    company: "Global SaaS Platform",
    description: "Lead product development across Vue, Node.js, GraphQL APIs, and AWS cloud infrastructure.",
    skills: ["Vue", "Node.js", "Full Stack", "GraphQL", "AWS"],
    location: "Gurgaon",
    jobType: "Full-time",
    workMode: "Onsite",
    salaryMin: 2200000,
    salaryMax: 3200000,
    salary: "₹22 - ₹32 LPA",
    status: "open",
    createdAt: new Date(),
  },

  // CLOUD & DEVOPS ROLES
  {
    _id: "global-devops-1",
    title: "Lead Cloud Infrastructure & Kubernetes Architect",
    companyName: "Amazon Web Services (AWS) Enterprise",
    company: "Amazon Web Services (AWS) Enterprise",
    description: "Managing enterprise Kubernetes multi-region clusters, Terraform Infrastructure as Code, and zero-downtime deployment pipelines.",
    skills: ["AWS", "Kubernetes", "DevOps", "Cloud & DevOps", "Terraform", "Docker", "CI/CD"],
    location: "Gurgaon",
    jobType: "Full-time",
    workMode: "Hybrid",
    salaryMin: 4000000,
    salaryMax: 6500000,
    salary: "₹40 - ₹65 LPA",
    experienceRequired: 6,
    status: "open",
    createdAt: new Date(),
  },
  {
    _id: "mock-4",
    title: "Cloud & DevOps Infrastructure Specialist",
    companyName: "CloudScale Systems",
    company: "CloudScale Systems",
    description: "Automating CI/CD pipelines, Docker container orchestration, Kubernetes clusters, and AWS infrastructure.",
    skills: ["AWS", "Docker", "Kubernetes", "DevOps", "Cloud & DevOps", "Cloud"],
    location: "Gurgaon",
    jobType: "Full-time",
    workMode: "Onsite",
    salaryMin: 2000000,
    salaryMax: 3200000,
    salary: "₹20 - ₹32 LPA",
    status: "open",
    createdAt: new Date(),
  },
  {
    _id: "mock-5",
    title: "Senior AWS Cloud Architect & Security Lead",
    companyName: "HyperCloud Infrastructure",
    company: "HyperCloud Infrastructure",
    description: "Architecting zero-trust cloud security solutions, Terraform IaC, AWS Lambda, and Kubernetes microservices.",
    skills: ["AWS", "Terraform", "Cloud", "DevOps", "Kubernetes", "Security", "Cloud & DevOps"],
    location: "Bangalore",
    jobType: "Full-time",
    workMode: "Remote",
    salaryMin: 2500000,
    salaryMax: 3800000,
    salary: "₹25 - ₹38 LPA",
    status: "open",
    createdAt: new Date(),
  },
  {
    _id: "mock-12",
    title: "Site Reliability Engineer (SRE / Kubernetes)",
    companyName: "ScaleScale Global",
    company: "ScaleScale Global",
    description: "Ensuring 99.999% system uptime, Prometheus monitoring, Grafana dashboards, and automated failovers.",
    skills: ["Kubernetes", "DevOps", "Cloud & DevOps", "SRE", "Linux", "AWS"],
    location: "Hyderabad",
    jobType: "Full-time",
    workMode: "Hybrid",
    salaryMin: 2100000,
    salaryMax: 3300000,
    salary: "₹21 - ₹33 LPA",
    status: "open",
    createdAt: new Date(),
  },
];

module.exports = { mockJobsData: worldJobDatabase };
